**Vector Matrix and Arrays**

Create a Vector

In [ ]:
# list of numbers
#dot product
import numpy as np

vector_row = np.array([1, 2, 3])
print(vector_row)
vector_col = np.array([
    [1],
    [2],
    [3]
])
print(vector_col)

# (r,c) (mxn)
# row vector = (1,m)
# column vector = (m,1)

[1 2 3]
[[1]
 [2]
 [3]]


Create a matrix

In [ ]:
matrix = np.array([
    [1,2],
    [2,3],
    [3,4]
])
print(matrix)
print(matrix.shape)
print(vector_col.shape)
print(type(matrix))

[[1 2]
 [2 3]
 [3 4]]
(3, 2)
(3, 1)
<class 'numpy.ndarray'>


In [ ]:
matx = np.mat([
    [1,2],
    [2,3],
    [3,4]
])

print(matx)
print(matx.shape)
print(type(matx))

#which one to use. np.mat = no. np.array

[[1 2]
 [2 3]
 [3 4]]
(3, 2)
<class 'numpy.matrix'>


Create a Sparse Matrix

In [ ]:
#movie review netflix 10,000 1000
import numpy as np
from scipy import sparse
matx = np.mat([
    [0,0],
    [2,0],
    [3,0]
])

# print(matx)
sparse_mat = sparse.csr_matrix(matx)
print(sparse_mat)

  (1, 0)	2
  (2, 0)	3


Selecting Elements in vector and matrix

In [ ]:
vector_row = np.array([1, 2, 3])
# print(vector_row)
vector_col = np.array([
    [1],
    [2],
    [3]
])

print(vector_row[1])


2


In [ ]:
matx = np.mat([
    [1,2],
    [2,3],
    [3,4]
])

print(matx[2,0])

3


Describe a matrix

In [ ]:
import numpy as np
matrix = np.array([[1,2,3,4],
                   [4,5,6,7]])
print(matrix)

[[1 2 3 4]
 [4 5 6 7]]


In [ ]:
matrix.shape
matrix.size
matrix.ndim

2

Numpy Array

In [ ]:
list1 = [1,2,4,5]
print(list1*3)

numpylist = np.array(list1)
print(numpylist*3)

[1, 2, 4, 5, 1, 2, 4, 5, 1, 2, 4, 5]
[ 3  6 12 15]


Operations in Numpy Array

In [ ]:
matrix = np.array([[1, 2, 3],
 [4, 5, 6],
 [7, 8, 9],
])

matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Finding the maximum and minimum values

In [ ]:
# print(matrix)
# min subset array
# (r,c) = (0,1)

np.min(matrix,axis=1)


array([1, 4, 7, 7])

Average, Variance, Standard Deviation

In [ ]:
np.mean(matrix)
np.var(matrix)
np.std(matrix)

2.6180463454008347

Reshaping Array

In [ ]:
print(matrix) #r*c = 12

matrix.reshape(4,-1) #r,c

[[1 2 3]
 [4 5 6]
 [7 8 9]
 [7 8 9]]


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [7, 8, 9]])

Vector or Matrix Transpose

In [ ]:
# print(matrix)
# matrix.T
np.array([[1,2,3]]).T

array([[1],
       [2],
       [3]])

Flattening a Matrix

In [ ]:
print(matrix)
print(matrix.flatten())
print(matrix.reshape(1,-1)) #r,c

[[1 2 3]
 [4 5 6]
 [7 8 9]
 [7 8 9]]
[1 2 3 4 5 6 7 8 9 7 8 9]
[[1 2 3 4 5 6 7 8 9 7 8 9]]


Calculating Determinant

In [ ]:
print(matrix)

np.linalg.det(matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


0.0

Diagonal of a Matrix

In [ ]:
matrix.diagonal()

array([1, 5, 9])

Trace of a matrix (sum of diagonal elements)

In [ ]:
# matrix.trace()
sum(matrix.diagonal())

15

Eigenvalues and Eigenvectors

In [ ]:
print(matrix)

egvalue, egvector = np.linalg.eig(matrix)
print(egvalue)
print(egvector)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[ 1.61168440e+01 -1.11684397e+00 -1.30367773e-15]
[[-0.23197069 -0.78583024  0.40824829]
 [-0.52532209 -0.08675134 -0.81649658]
 [-0.8186735   0.61232756  0.40824829]]


Dot Product

In [ ]:
vector_a = np.array([1,2,3])
vector_b = np.array([4,5,6])

# np.dot(vector_a, vector_b)

vector_a @ vector_b

32

Adding and Substracting Matrices

In [ ]:
np.add(vector_a, vector_b)
np.subtract(vector_a,vector_b)

array([-3, -3, -3])

Matrix Inversion

In [ ]:
matrix = np.array([[1, 4],
 [2, 5]])
np.linalg.inv(matrix)

array([[-1.66666667,  1.33333333],
       [ 0.66666667, -0.33333333]])

Random Value Generation

In [ ]:
np.random.random(3) #0-1
np.random.randint(0,11,3)
#distribution
np.random.normal(0,1,3)
#logistic, uniform

array([ 0.64588751, -0.62095636, -1.82488782])